version: "3.9"

services:
  api-dev:
    build: .
    container_name: APIHorse
    ports:
      - "9050:9050"
    volumes:
      - ./Linux64/Debug:/usr/sbin
    entrypoint: ["/usr/sbin/docker_example_server"]

    #db:
    #  image: postgres:latest
    #  enviroment:
    #    POSTGRES_USER: user
    #    POSTGRES_PASSWORD: password
    #    POSTGRES_DB: mydatabase