CREATE TABLE cliente (
    id INTEGER NOT NULL PRIMARY KEY,
    nome VARCHAR(50),
    sobrenome VARCHAR(50),
    email VARCHAR(100),
    telefone VARCHAR(20)
);

INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (1, 'João', 'Silva', 'joao.silva@email.com', '123456789');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (2, 'Maria', 'Oliveira', 'maria.oliveira@email.com', '987654321');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (3, 'Pedro', 'Santos', 'pedro.santos@email.com', '555555555');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (4, 'Ana', 'Souza', 'ana.souza@email.com', '444444444');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (5, 'Lucas', 'Costa', 'lucas.costa@email.com', '333333333');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (6, 'Fernanda', 'Gomes', 'fernanda.gomes@email.com', '222222222');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (7, 'Carlos', 'Pereira', 'carlos.pereira@email.com', '111111111');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (8, 'Juliana', 'Rodrigues', 'juliana.rodrigues@email.com', '666666666');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (9, 'Ricardo', 'Alves', 'ricardo.alves@email.com', '777777777');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (10, 'Tatiane', 'Moraes', 'tatiane.moraes@email.com', '888888888');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (11, 'Daniel', 'Azevedo', 'daniel.azevedo@email.com', '999999999');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (12, 'Roberta', 'Barbosa', 'roberta.barbosa@email.com', '101010101');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (13, 'Renato', 'Lima', 'renato.lima@email.com', '111111222');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (14, 'Beatriz', 'Ferreira', 'beatriz.ferreira@email.com', '121212121');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (15, 'Marcelo', 'Dias', 'marcelo.dias@email.com', '131313131');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (16, 'Aline', 'Martins', 'aline.martins@email.com', '141414141');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (17, 'Vinicius', 'Nascimento', 'vinicius.nascimento@email.com', '151515151');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (18, 'Cláudia', 'Farias', 'claudia.farias@email.com', '161616161');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (19, 'Fabio', 'Mendes', 'fabio.mendes@email.com', '171717171');
INSERT INTO cliente (id, nome, sobrenome, email, telefone) VALUES (20, 'Patrícia', 'Ribeiro', 'patricia.ribeiro@email.com', '181818181');


CREATE TABLE PRODUTOS (
    ID_PRODUTO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    DESCRICAO_PRODUTO VARCHAR(255),
    PRECO DECIMAL(15, 2) NOT NULL,
    QUANTIDADE_ESTOQUE INTEGER NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Mouse Gamer', 'Mouse com 7 botões e luz LED RGB', 150.00, 50);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Teclado Mecânico', 'Teclado mecânico com switches Blue', 250.00, 30);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Monitor 24"', 'Monitor LED Full HD de 24 polegadas', 900.00, 20);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Cadeira Gamer', 'Cadeira ergonômica com ajuste de altura', 1200.00, 10);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Headset Bluetooth', 'Headset sem fio com microfone', 300.00, 40);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Notebook i5', 'Notebook com processador Intel Core i5', 3500.00, 15);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Impressora Laser', 'Impressora laser monocromática', 800.00, 25);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Webcam Full HD', 'Webcam com resolução 1080p', 250.00, 35);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('HD Externo 1TB', 'HD externo portátil de 1TB', 400.00, 60);

INSERT INTO PRODUTOS (NOME_PRODUTO, DESCRICAO_PRODUTO, PRECO, QUANTIDADE_ESTOQUE)
VALUES ('Smartphone Android', 'Smartphone com 64GB de armazenamento', 2000.00, 20);
